function [Pss_single,Pss_compare]=bsliang_getPvalues(Pstructure)

    Pss_single=nan(4,4);
    Pss_compare=nan(4,2);
    
    % left_clear
    Pss_single(1,:) = [Pstructure.left_clear.tone_iTBS ...
                       Pstructure.left_clear.tone_cTBS ...
                       Pstructure.left_clear.phon_iTBS ...
                       Pstructure.left_clear.phon_cTBS];
                   
    Pss_compare(1,:) = [Pstructure.left_clear.tone_icTBS ...
                       Pstructure.left_clear.phon_icTBS];
                   
    % right_clear
    Pss_single(2,:) = [Pstructure.right_clear.tone_iTBS ...
                       Pstructure.right_clear.tone_cTBS ...
                       Pstructure.right_clear.phon_iTBS ...
                       Pstructure.right_clear.phon_cTBS];
                   
    Pss_compare(2,:) = [Pstructure.right_clear.tone_icTBS ...
                       Pstructure.right_clear.phon_icTBS];
                   
    % left_noise
    Pss_single(3,:) = [Pstructure.left_noise.tone_iTBS ...
                       Pstructure.left_noise.tone_cTBS ...
                       Pstructure.left_noise.phon_iTBS ...
                       Pstructure.left_noise.phon_cTBS];
                   
    Pss_compare(3,:) = [Pstructure.left_noise.tone_icTBS ...
                       Pstructure.left_noise.phon_icTBS];
                   
    % right_noise
    Pss_single(4,:) = [Pstructure.right_noise.tone_iTBS ...
                       Pstructure.right_noise.tone_cTBS ...
                       Pstructure.right_noise.phon_iTBS ...
                       Pstructure.right_noise.phon_cTBS];
                   
    Pss_compare(4,:) = [Pstructure.right_noise.tone_icTBS ...
                       Pstructure.right_noise.phon_icTBS];