function bsliang_bar(center,height,extent,lw,col)
% a self-made bar plot
plot([center-extent center-extent center+extent center+extent],...
     [0 height height 0],...
     'LineWidth',lw,'Color',col);